my_string = input('Ваше ФИО: ')
print(len(my_string))
print('Здравствуйте, ',my_string .upper())
print('Здравствуйте, ',my_string .lower())
print('Здравствуйте, ',my_string .replace(' ', '') )
print(my_string[0])
print(my_string [-1])